name: Commit Build

on:
  push:
    branches: 
      - master
      - dev
    tags-ignore:
      - v*

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v3.x
        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install libncurses-dev
          make
          make clean
          rm -rf .git*

      - name: List Output
        run: |
          cd Binary
          ls -l
          find -type f -exec md5sum '{}' \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: RomWBW_Linux-${{env.GITHUB_REF_SLUG}}-${{env.GITHUB_SHA_SHORT}}
          path: .

  buildMacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          make
          make clean
          rm -rf .git*

      - name: List Output
        run: |
          cd Binary
          ls -l
          find . -type f -exec md5 -r -- '{}' +;

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: RomWBW_MacOS
          path: .
